- name : the conditions practice
  hosts: web
  become: yes
  vars_prompt:
    - name: my_number
      prompt: Please enter the number
      private: false
  tasks:
    - name: The conditions checking
      ansible.builtin.debug:
        msg: "The number {{my_number}} is  greter than 100"
      when: my_number > 100

    - name: the less than condition check
      ansible.builtin.debug:
        msg: "The number {{my_number}} is  less than 100"
      when: my_number <= 100    