- name: loops practice
  hosts: web
  become: yes
  tasks:
  - name: This is the loop practice 
    debug:
      msg: "  the  List names are in package is: {{item}} "
    loop:
      - sankar
      - ram
      - robert
      - rahim

  - name: This is loops with map type 
    debug:
      msg: "This is list of key {{item.id, item.val}}"   
    loop:
      - {id: 01, val: "java"}

  - name: This is the loops with software installation
    package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
      - {name: 'mysql', state: 'present'}
      - {name: 'nginx', state: 'absent'}