- name: loops practice
  hosts: web
  tasks:
  - name: This is the loop practice 
    ansible.builtin.debug:
      msg: "  the  List names: {{item}} "
    loop:
      - sankar
      - ram
      - robert
      - rahim

  - name: This is loops with map type 
    ansible.builtin.debug:
      msg: "This is list of key {{item.id , item.val}}"   
    loop:
      {id: 01, val: "java"}