- name: String ManiPulation
  hosts: web
  vars:
    string1: " I am learing Ansible"
  tasks:
  - name: Upper case
    debug:
      msg: " The String in Upper case::  {{string1 | upper }}"

  - name: Lower case
    debug:
      msg: " The String in Upper case::  {{string1 | lower }}, {{string1 | capitalize}}"
    
  - name: Split String
    vars:
      string3: " I am Ansible"
    set_fact:
      my_string: "{{string3 | trim | split (' ') }}"

  - name: mystring validation
    set_fact:
     my_string: "{{my_string +['automation']}}"
    when: "'Ansible' in my_string "

  - name: item assignment
    set_fact:
      variable1: "{{item}}"
    when: item =='Ansible'
    loop: "{{ my_string }}"

  - name: The item assignment
    debug:
      msg: " The String in Upper case:: {{variable1}} , {{ my_string }} "

  - name: deafault varible assignment
    vars:
      variable2: "{{corse | default('admin')}}"
    debug:
      msg: "The variable 2 is: {{variable2}} , the variable 3 is {{course | default('admin')}} "
  
  - name:  the defuat values for list
    vars: 
      courses:
         A: java
         B: devops
         C: python
    debug:
      msg: "{{item}}"
    loop: "{{courses | dict2items}}"    

  - name:  the number minimum, maximum and unique and distinct
    vars: 
      numbers: [1,4,45,3,1,2,3]
    debug:
      msg: "Min :: {{numbers | min }} max:: {{numbers | max }} uniquie :: {{numbers | unique }}"
    


      
