- name: String ManiPulation
  hosts: web
  vars:
    string1: " I am learing Ansible"
  tasks:
  - name: Upper case
    debug:
      msg: " The String in Upper case::  {{string1 | upper }}"

  - name: Lower case
    debug:
      msg: " The String in Upper case::  {{string1 | lower }}, {{string1 | capitalize}}"
    
  - name: Split String
    vars:
      string3: " I am Ansible"
    set_fact:
      my_string: "{{string3 | trim | split (' ') }}"

  - name: mystring validation
    set_fact:
     my_string: "{{my_string +['automation']}}"
    loop: "{{ my_string }}"

  - name: item assignment
    set_fact:
     ans-variable: {{item}}
    when: item =='Ansible'
    loop: "{{ my_string }}"

  - name: The item assignment
    debug:
      msg: " The String in Upper case:: {{ans-variable}} , {{ my_string }} "
    


      
