- name: String ManiPulation
  hosts: web
  vars:
    string1: " I am learing Ansible"
  tasks:
  - name: Upper case
    vars:
      string3: " i am  learning Ansible"
    debug:
      msg: " The String in Upper case::  {{string1 | upper }}"

  - name: Lower case
    debug:
      msg: " The String in Upper case::  {{string1 | lower }}, {{string1 | capitalize}}"
    
  - name: Split String
    set_fact:
      my_string: "{{string3 | split(' ')}}"
    

  - name: Assign the Split String
    vars:
      string4: " I am learing Ansible"
    debug:
      msg: " The String in Upper case::  {{my_string}}"



      
