- name: create the ec2 and route 53 instance
  hosts: local
  connection: local
  vars:
    subnet_id: 
    sg-id: 
    ami_id: 
    zone: "sankardevops.shop"
  instances: 
    - mysql
    - backend
    - frontend
  tasks:
    amazon.aws.ec2_instance:
    name: private instances creation
    vpc_subnet_id: "{{subnet_id}}"
    instance_type: "t3.micro"
    security_group: "{{sg-id}}"
    image_id: ami-123456
  loop: "{{instances}}"
  register: ec2_instances

- name: The ec2- instance creation results
  debug:
    msg: " The Results are::  {{ec2_instances}}"