- name: create the ec2 and route 53 instance
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-053e9fc2e2cae9a0a
    sg_id: "sg-041ee0572bd9bc6ca"
    ami_id: "ami-09c813fb71547fc4f"
    zone: "sankardevops.shop"
    instances: 
      - mysql
      - backend
      - frontend
  tasks:
  - name: The private instances creation
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: "t3.micro"
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: The reslts
    debug:
      msg: "The reslts are {{ec2_instances}}"   

  - name: The route 53
    amazon.aws.route53:
       state: present
       zone: "{{zone}}"
       record: "{{item.item}}.{{zone}}"
       type: A
       ttl: 1
       value: "{{item.instances[0].private_ip_address}}"
       wait: true
       overwrite: True
    loop: "{{ec2_instances.results}}"

  - name: The route public record
    amazon.aws.route53:
       state: present
       zone: "{{zone}}"
       record: "{{zone}}"
       type: A
       ttl: 1
       value: "{{item.instances[0].public_ip_address}}"
       wait: true
       overwrite: True
    loop: "{{ec2_instances.results}}"
    when: item:item == 'frontend'
    